name: 'Rise Slack Action'
description: 'Send A Custom Or Pre-Defined Slack Message Using GitHub Actions'
branding:
  icon: message-circle
  color: white
inputs:
  status:
    description: 'Set to started / success / failed / custom'
    required: true
  version:
    description: 'Pass tag version for success message'
    required: false
  endpoint:
    # Change to the production channel when action is finished.
    description: 'endpoint of a service'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.status }}
    - ${{ inputs.version}}
    - ${{ inputs.endpoint}}