name: Build Service
on:
  push:
    branches:
      - main

env:
  PROJECT_NAME:           ${{ github.event.repository.name }}
  AWS_ACCESS_KEY_ID:      ${{ secrets.aws_access_key }}
  AWS_SECRET_ACCESS_KEY:  ${{ secrets.aws_secret_key }}
  AWS_REGION:             us-east-1
  # Dynamics:
  ENVIRONMENT:            ${{ github.ref_name }}

jobs:
  Build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ github.event.repository.name }}
      run: |
        tag_v=$(git describe --tags $(git rev-list --tags --max-count=1))
        git push --delete origin tag_v
        git tag tag_v
        git push --tags
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.ENVIRONMENT }}_${tag_v} .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.ENVIRONMENT }}_${tag_v} .
